# Generated by Django 2.2 on 2021-04-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_playlist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers'),
        ),
    ]
