# Generated by Django 2.2 on 2021-05-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20210424_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.CharField(help_text='Введите автора трека', max_length=255, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(help_text='Введите название трека', max_length=255, verbose_name='Название'),
        ),
    ]
